### PR TITLE
feat(): create map4

### PR DESCRIPTION
**Pull request by wandroll**
##What this PR does / why we need it:

I'd like to have a map4 ( like we have already a map3 / map2

### CODE REVIEW

**Comment by guillaumewuip** [comment]
Given the kind high number (4), maybe is something like that https://gcanti.github.io/fp-ts/modules/Apply.ts.html#sequences-function also well suited to your need ?

The idea behind that would be to convert an array of Dataway into a Dataway of array.

Example:

```ts
const a: [Dataway<E, T1>, Dataway<E, T2>] = ...;
const b: Dataway<E, [T1, T2]> = somemagic(a);
```

The idea is to stop adding mapX and prefer a more generic approach.
What do you think ?

**Comment by guillaumewuip** [comment]
Just tried 

```ts
const tranform = sequenceT(dataway);

const dataway1: Dataway<Error, string> = success('hello');
const dataway2: Dataway<Error, number> = success(123);

const datawayOfArray: Dataway<Error, [string, number]> = tranform(
  dataway1,
  dataway2
);
```

And this works out of the box

**Comment by wandroll** [comment]
> Just tried
> 
> ```ts
> import { dataway, Dataway, success } from 'dataway';
> import { sequenceT } from 'fp-ts/lib/Apply';
> 
> const transform = sequenceT(dataway);
> 
> const dataway1: Dataway<Error, string> = success('hello');
> const dataway2: Dataway<Error, number> = success(123);
> 
> const datawayOfArray: Dataway<Error, [string, number]> = transform(
>   dataway1,
>   dataway2
> );
> ```
> 
> And this works out of the box

ha ha , I was on the same track. Awesome, thanks

**Comment by guillaumewuip** [comment]
Nice ! Can we close the PR then ?

**Pull request closed without merging**
